name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run coverage
      # Cannot do race testing because it needs CGO.
        run: go test -coverprofile=coverage.xml -covermode=atomic -v ./...
        env:
          CGO_ENABLED: 0
          TF_ACC: 1
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          version: "v0.1.15"
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
